### ISSUE TITLE
Helper Pods Run Hardcoded Images 

### ISSUE THREAD

**Issue by George-Aeillo** [oracle-cne/ocne#166]
When Helper Pods are used in various OCNE commands, they run hardcoded images that are hosted on Oracle Container Registry. This can cause issues for users that are running the CLI in air-gapped environments, as they may not have access to the public internet to download these images. This should be changed to allow users to specify where to download images for the helper pods used in the CLI.

**Comment by prasad-shirodkar** [comment]
`toolbox` image is not copied by the mirror functionality (`ocne catalog mirror`) to the private registry. We should account for toolbox image too in air-gapped environment.
https://github.com/oracle-cne/ocne/blob/f4cbeb3099e374cc432e919c2dea09527db6effb/pkg/k8s/pod.go#L117

**Comment by George-Aeillo** [comment]
Closing this issue, as this issue is duplicated by a more recent issue https://github.com/oracle-cne/ocne/issues/196.
