### ISSUE TITLE
Add feature to specify multiple registries

### ISSUE THREAD

**Issue by Raaghavcodes** [oracle-cne/ocne#195]
Allow the user to specify multiple registries in the cluster configuration and defaults file. This will allow the user to store their images in more than one repository. For example, if a user does not have all images in their custom repository, they may specify container-registry.oracle.com as a registry and avoid any image pull issues.

**Comment by George-Aeillo** [comment]
After discussing with the team, adding multiple unqualified registries will not be done natively through the CLI, but a user can configure these settings through a custom image built with ock-forge, or additional Ignition configuration.
